[snowflake]
user = "kipisky"
password = "Kipi@123"
account = "dzezein-rd61427"
warehouse = "Retail_WH"
database = "Retail_DB"
schema = "Retail_SCHEMA"


[passwords]
alice_foo = "streamlit123"
bob_bar = "mycrazypw"
