[snowflake]
user = "kipisky"
password = "Kipi@123"
account = "jmbwnqr-dm28713"
warehouse = "ML_MODEL_WH"
database = "MLMODEL_DB"
schema = "ML_MODEL_WH"


[passwords]
Craig = "Craig123"
Jhony = "Jhony123"

[theme]
primaryColor="#F63366"
backgroundColor="#07268B"
secondaryBackgroundColora="#31333F"
textColor="#FAFAFA"
font="sans serif"
