[snowflake]
user = "kipisky"
password = "Kipi@123"
account = "dzezein-rd61427"
warehouse = "Retail_WH"
database = "Retail_DB"
schema = "Retail_SCHEMA"


[passwords]
streamlit1 = "streamlit123"
streamlit2 = "streamlit123"
